//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace RP.Model
{
    public partial class BUNotificationEmail
    {
        public int Id { get; set; }
        public int BuId { get; set; }
        public string Email { get; set; }
        public int BuEmailTypeId { get; set; }
    
        public virtual BuEmailType BuEmailType { get; set; }
        public virtual BusinessUnit BusinessUnit { get; set; }
    }
    
}
