//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace RP.Model
{
    public partial class BusinessUnit
    {
        public BusinessUnit()
        {
            this.BUNotificationEmails = new HashSet<BUNotificationEmail>();
            this.BuSuppliers = new HashSet<BuSupplier>();
            this.Routes = new HashSet<Route>();
            this.Suppliers = new HashSet<Supplier>();
            this.Tariffs = new HashSet<Tariff>();
            this.Transports = new HashSet<Transport>();
            this.TransportDrafts = new HashSet<TransportDraft>();
            this.TransportHistories = new HashSet<TransportHistory>();
            this.Users = new HashSet<User>();
        }
    
        public int Id { get; set; }
        public int CountryId { get; set; }
        public Nullable<int> TimezoneId { get; set; }
        public string Name { get; set; }
        public decimal Handicap90 { get; set; }
        public decimal Handicap80 { get; set; }
        public decimal Handicap70 { get; set; }
        public decimal Handicap60 { get; set; }
        public decimal Handicap50 { get; set; }
        public decimal HandicapLessThan50 { get; set; }
        public decimal CostPerDay { get; set; }
        public decimal MaxCostPerDay { get; set; }
        public string Address { get; set; }
        public string Phone { get; set; }
        public string Fax { get; set; }
        public bool IsDeleted { get; set; }
        public byte[] Logo { get; set; }
        public Nullable<int> LimitRealDateArrival { get; set; }
        public Nullable<bool> IsDisplayDistanceOverMsg { get; set; }
    
        public virtual ICollection<BUNotificationEmail> BUNotificationEmails { get; set; }
        public virtual Country Country { get; set; }
        public virtual TimeZone TimeZone { get; set; }
        public virtual ICollection<BuSupplier> BuSuppliers { get; set; }
        public virtual ICollection<Route> Routes { get; set; }
        public virtual ICollection<Supplier> Suppliers { get; set; }
        public virtual ICollection<Tariff> Tariffs { get; set; }
        public virtual ICollection<Transport> Transports { get; set; }
        public virtual ICollection<TransportDraft> TransportDrafts { get; set; }
        public virtual ICollection<TransportHistory> TransportHistories { get; set; }
        public virtual ICollection<User> Users { get; set; }
    }
    
}
