//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace RP.Model
{
    public partial class Country
    {
        public Country()
        {
            this.BusinessUnits = new HashSet<BusinessUnit>();
            this.Routes = new HashSet<Route>();
            this.Routes1 = new HashSet<Route>();
            this.Suppliers = new HashSet<Supplier>();
            this.TariffMinimumKmCountries = new HashSet<TariffMinimumKmCountry>();
            this.TariffSurchargeCountries = new HashSet<TariffSurchargeCountry>();
            this.TransportLocations = new HashSet<TransportLocation>();
            this.TransportLocations1 = new HashSet<TransportLocation>();
            this.TransportLocationDrafts = new HashSet<TransportLocationDraft>();
            this.TransportLocationDrafts1 = new HashSet<TransportLocationDraft>();
        }
    
        public int Id { get; set; }
        public string Key { get; set; }
        public string Name { get; set; }
        public string Code { get; set; }
        public string FlagIcon { get; set; }
        public int CurrencyId { get; set; }
    
        public virtual ICollection<BusinessUnit> BusinessUnits { get; set; }
        public virtual Currency Currency { get; set; }
        public virtual ICollection<Route> Routes { get; set; }
        public virtual ICollection<Route> Routes1 { get; set; }
        public virtual ICollection<Supplier> Suppliers { get; set; }
        public virtual ICollection<TariffMinimumKmCountry> TariffMinimumKmCountries { get; set; }
        public virtual ICollection<TariffSurchargeCountry> TariffSurchargeCountries { get; set; }
        public virtual ICollection<TransportLocation> TransportLocations { get; set; }
        public virtual ICollection<TransportLocation> TransportLocations1 { get; set; }
        public virtual ICollection<TransportLocationDraft> TransportLocationDrafts { get; set; }
        public virtual ICollection<TransportLocationDraft> TransportLocationDrafts1 { get; set; }
    }
    
}
