//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace RP.Model
{
    public partial class Currency
    {
        public Currency()
        {
            this.Countries = new HashSet<Country>();
            this.CurrencyRates = new HashSet<CurrencyRate>();
            this.Quotes = new HashSet<Quote>();
            this.TransportReferences = new HashSet<TransportReference>();
            this.TransportReferenceDrafts = new HashSet<TransportReferenceDraft>();
        }
    
        public int Id { get; set; }
        public string Key { get; set; }
        public string Name { get; set; }
        public string Code { get; set; }
        public string Symbol { get; set; }
    
        public virtual ICollection<Country> Countries { get; set; }
        public virtual ICollection<CurrencyRate> CurrencyRates { get; set; }
        public virtual ICollection<Quote> Quotes { get; set; }
        public virtual ICollection<TransportReference> TransportReferences { get; set; }
        public virtual ICollection<TransportReferenceDraft> TransportReferenceDrafts { get; set; }
    }
    
}
