//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace RP.Model
{
    public partial class CustomerBranch
    {
        public CustomerBranch()
        {
            this.Documents = new HashSet<Document>();
        }
    
        public System.Guid Id { get; set; }
        public string CustomerBranchName { get; set; }
        public System.Guid CustomerId { get; set; }
        public System.Guid RegionId { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual Region Region { get; set; }
        public virtual ICollection<Document> Documents { get; set; }
    }
    
}
