//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace RP.Model
{
    public partial class ProductMaterialUsage
    {
        public System.Guid Id { get; set; }
        public System.Guid ProductId { get; set; }
        public Nullable<System.Guid> MaterialId { get; set; }
        public System.Guid MaterialUnitId { get; set; }
        public Nullable<int> Amount { get; set; }
        public System.Guid ProductUnitId { get; set; }
    
        public virtual MaterialUnit MaterialUnit { get; set; }
        public virtual Product Product { get; set; }
        public virtual Unit Unit { get; set; }
    }
    
}
