//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace RP.Model
{
    public partial class QuoteHistory
    {
        public int Id { get; set; }
        public int QuoteId { get; set; }
        public decimal QuoteAmount { get; set; }
        public int CurrencyId { get; set; }
        public decimal CurrencyRate { get; set; }
        public int DeliveryDuration { get; set; }
        public int LastUpdatedBy { get; set; }
        public System.DateTime LastUpdatedDate { get; set; }
        public Nullable<System.DateTime> ExpectedPickUpDate { get; set; }
    
        public virtual Quote Quote { get; set; }
    }
    
}
