//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace RP.Model
{
    public partial class Route
    {
        public Route()
        {
            this.RouteSuppliers = new HashSet<RouteSupplier>();
        }
    
        public int Id { get; set; }
        public int BuId { get; set; }
        public int PickupCountryId { get; set; }
        public int DeliveryCountryId { get; set; }
        public int PreferredSupplierId { get; set; }
        public int BackupSupplierId { get; set; }
        public int ExpirationTime { get; set; }
        public int DeliveryTime { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<int> LastUpdatedBy { get; set; }
        public System.DateTime LastUpdatedDate { get; set; }
        public Nullable<int> ExpressDelivery { get; set; }
        public int MinimumKm { get; set; }
        public int MaximumKm { get; set; }
    
        public virtual BusinessUnit BusinessUnit { get; set; }
        public virtual Country Country { get; set; }
        public virtual Country Country1 { get; set; }
        public virtual Supplier Supplier { get; set; }
        public virtual Supplier Supplier1 { get; set; }
        public virtual ICollection<RouteSupplier> RouteSuppliers { get; set; }
    }
    
}
