//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace RP.Model
{
    public partial class Supplier
    {
        public Supplier()
        {
            this.BuSuppliers = new HashSet<BuSupplier>();
            this.Quotes = new HashSet<Quote>();
            this.Routes = new HashSet<Route>();
            this.Routes1 = new HashSet<Route>();
            this.RouteSuppliers = new HashSet<RouteSupplier>();
            this.SupplierEmails = new HashSet<SupplierEmail>();
            this.Tariffs = new HashSet<Tariff>();
            this.Transports = new HashSet<Transport>();
            this.TransportDrafts = new HashSet<TransportDraft>();
            this.TransportHistories = new HashSet<TransportHistory>();
            this.TransportSuppliers = new HashSet<TransportSupplier>();
            this.Users = new HashSet<User>();
        }
    
        public int Id { get; set; }
        public Nullable<int> BuId { get; set; }
        public int CountryId { get; set; }
        public int TimezoneId { get; set; }
        public string Name { get; set; }
        public int SupplierTypeId { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<int> LastUpdatedBy { get; set; }
        public System.DateTime LastUpdatedDate { get; set; }
        public string SupAddress { get; set; }
        public byte[] Logo { get; set; }
        public string PhoneNo { get; set; }
        public Nullable<System.DateTime> WorkingHourOpen { get; set; }
        public Nullable<System.DateTime> WorkingHourClose { get; set; }
    
        public virtual BusinessUnit BusinessUnit { get; set; }
        public virtual ICollection<BuSupplier> BuSuppliers { get; set; }
        public virtual Country Country { get; set; }
        public virtual ICollection<Quote> Quotes { get; set; }
        public virtual ICollection<Route> Routes { get; set; }
        public virtual ICollection<Route> Routes1 { get; set; }
        public virtual ICollection<RouteSupplier> RouteSuppliers { get; set; }
        public virtual SupplierType SupplierType { get; set; }
        public virtual TimeZone TimeZone { get; set; }
        public virtual ICollection<SupplierEmail> SupplierEmails { get; set; }
        public virtual ICollection<Tariff> Tariffs { get; set; }
        public virtual ICollection<Transport> Transports { get; set; }
        public virtual ICollection<TransportDraft> TransportDrafts { get; set; }
        public virtual ICollection<TransportHistory> TransportHistories { get; set; }
        public virtual ICollection<TransportSupplier> TransportSuppliers { get; set; }
        public virtual ICollection<User> Users { get; set; }
    }
    
}
