//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace RP.Model
{
    public partial class SupplierType
    {
        public SupplierType()
        {
            this.Suppliers = new HashSet<Supplier>();
        }
    
        public int Id { get; set; }
        public string Key { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<Supplier> Suppliers { get; set; }
    }
    
}
