//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace RP.Model
{
    public partial class SupplierEmailType
    {
        public SupplierEmailType()
        {
            this.SupplierEmails = new HashSet<SupplierEmail>();
        }
    
        public int Id { get; set; }
        public string Key { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<SupplierEmail> SupplierEmails { get; set; }
    }
    
}
