//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace RP.Model
{
    public partial class TariffSurcharge
    {
        public TariffSurcharge()
        {
            this.TariffSurchargeCountries = new HashSet<TariffSurchargeCountry>();
        }
    
        public int Id { get; set; }
        public int TariffId { get; set; }
        public string Description { get; set; }
        public decimal Surcharge { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int LastUpdatedBy { get; set; }
        public System.DateTime LastUpdatedDate { get; set; }
        public bool IsDeleted { get; set; }
    
        public virtual Tariff Tariff { get; set; }
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
        public virtual ICollection<TariffSurchargeCountry> TariffSurchargeCountries { get; set; }
    }
    
}
