//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace RP.Model
{
    public partial class TariffExpressDeliveryVehicleDimension
    {
        public int Id { get; set; }
        public int TariffExpressDeliveryId { get; set; }
        public int VehicleDimensionId { get; set; }
        public bool IsDeleted { get; set; }
    
        public virtual TariffExpressDelivery TariffExpressDelivery { get; set; }
        public virtual VehicleDimension VehicleDimension { get; set; }
    }
    
}
