//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace RP.Model
{
    public partial class TariffCategoryVehicleType
    {
        public int Id { get; set; }
        public int TariffCategoryId { get; set; }
        public int VehicleTypeId { get; set; }
        public bool IsDeleted { get; set; }
    
        public virtual TariffCategory TariffCategory { get; set; }
        public virtual VehicleType VehicleType { get; set; }
    }
    
}
