//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace RP.Model
{
    public partial class Temp_Supplier_Confirmation
    {
        public int TransportId { get; set; }
        public int DelayTime { get; set; }
        public bool IsExpired { get; set; }
        public Nullable<int> HasQuote { get; set; }
    }
    
}
