//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace RP.Model
{
    public partial class TimeZone
    {
        public TimeZone()
        {
            this.BusinessUnits = new HashSet<BusinessUnit>();
            this.Suppliers = new HashSet<Supplier>();
        }
    
        public int Id { get; set; }
        public string TimeZone1 { get; set; }
        public string Display { get; set; }
        public Nullable<decimal> TimePriority { get; set; }
    
        public virtual ICollection<BusinessUnit> BusinessUnits { get; set; }
        public virtual ICollection<Supplier> Suppliers { get; set; }
    }
    
}
