//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace RP.Model
{
    public partial class TransportVehicle
    {
        public int TransportId { get; set; }
        public string VehicleLicensePlate { get; set; }
        public Nullable<int> VehicleBrandId { get; set; }
        public string VehicleBrand { get; set; }
        public Nullable<int> VehicleModelId { get; set; }
        public string VehicleModel { get; set; }
        public int VehicleTypeId { get; set; }
        public decimal VehicleWidth { get; set; }
        public decimal VehicleLength { get; set; }
        public decimal VehicleHeight { get; set; }
        public decimal VehicleWeight { get; set; }
        public string VehicleKeyLocation { get; set; }
        public string VehicleDocumentLocation { get; set; }
        public string VehicleTransmission { get; set; }
        public int VehicleConditionId { get; set; }
        public bool IsRollable { get; set; }
        public bool HasLuggage { get; set; }
        public string LuggageDescription { get; set; }
        public string PoliceReportLocation { get; set; }
        public string OtherDocument { get; set; }
        public int VehicleDimensionId { get; set; }
    
        public virtual Transport Transport { get; set; }
        public virtual VehicleCondition VehicleCondition { get; set; }
        public virtual VehicleDimension VehicleDimension { get; set; }
        public virtual VehicleMake VehicleMake { get; set; }
        public virtual VehicleModel VehicleModel1 { get; set; }
        public virtual VehicleType VehicleType { get; set; }
    }
    
}
