//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace RP.Model
{
    public partial class TransportReferenceDraft
    {
        public int TransportDraftId { get; set; }
        public Nullable<decimal> RefCost { get; set; }
        public Nullable<int> RefDeliveryTime { get; set; }
        public Nullable<decimal> RefCostPerDay { get; set; }
        public Nullable<decimal> RefMaxCostPerDay { get; set; }
        public Nullable<decimal> RefTco { get; set; }
        public Nullable<decimal> RefCurrencyRate { get; set; }
        public Nullable<int> RefCurrencyId { get; set; }
        public Nullable<decimal> RefHandicap { get; set; }
        public Nullable<decimal> RefExpressDeliveryPrice { get; set; }
        public Nullable<decimal> RefPenalty { get; set; }
    
        public virtual Currency Currency { get; set; }
        public virtual TransportDraft TransportDraft { get; set; }
    }
    
}
