//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace RP.Model
{
    public partial class Transport
    {
        public Transport()
        {
            this.Quotes = new HashSet<Quote>();
            this.TransportComments = new HashSet<TransportComment>();
            this.TransportHistories = new HashSet<TransportHistory>();
            this.TransportQuoteDeclineReasons = new HashSet<TransportQuoteDeclineReason>();
            this.TransportQuotes = new HashSet<TransportQuote>();
            this.TransportSuppliers = new HashSet<TransportSupplier>();
        }
    
        public int Id { get; set; }
        public int BuId { get; set; }
        public string FileNumber { get; set; }
        public string CustomerFirstName { get; set; }
        public string CustomerLastName { get; set; }
        public string CustomerPhone { get; set; }
        public bool IsBidding { get; set; }
        public int ExpirationTime { get; set; }
        public bool IsExpressDelivery { get; set; }
        public string Remarks { get; set; }
        public Nullable<System.DateTime> EstimateDateArrival { get; set; }
        public Nullable<System.DateTime> RealDateArrival { get; set; }
        public Nullable<int> TransportStatusId { get; set; }
        public Nullable<int> ConfirmedSupplierId { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<int> LastUpdatedBy { get; set; }
        public System.DateTime LastUpdatedDate { get; set; }
        public Nullable<System.DateTime> ExpirationDate { get; set; }
        public Nullable<int> ExpirationHour { get; set; }
        public string ExpenditureId { get; set; }
        public Nullable<int> ExpressDeliveryTime { get; set; }
        public Nullable<bool> IsExtendBuddingTime { get; set; }
        public Nullable<int> ExtraTime { get; set; }
    
        public virtual BusinessUnit BusinessUnit { get; set; }
        public virtual ICollection<Quote> Quotes { get; set; }
        public virtual Supplier Supplier { get; set; }
        public virtual TransportStatu TransportStatu { get; set; }
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
        public virtual TransportAdditionalItem TransportAdditionalItem { get; set; }
        public virtual ICollection<TransportComment> TransportComments { get; set; }
        public virtual ICollection<TransportHistory> TransportHistories { get; set; }
        public virtual TransportLocation TransportLocation { get; set; }
        public virtual ICollection<TransportQuoteDeclineReason> TransportQuoteDeclineReasons { get; set; }
        public virtual ICollection<TransportQuote> TransportQuotes { get; set; }
        public virtual TransportReference TransportReference { get; set; }
        public virtual ICollection<TransportSupplier> TransportSuppliers { get; set; }
        public virtual TransportVehicle TransportVehicle { get; set; }
    }
    
}
