//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace RP.Model
{
    public partial class TransportCount
    {
        public int BuId { get; set; }
        public int PickupCountryId { get; set; }
        public int DeliveryCountryId { get; set; }
        public int Count { get; set; }
    }
    
}
