//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace RP.Model
{
    public partial class TransportSupplier
    {
        public int Id { get; set; }
        public int TransportId { get; set; }
        public int SupplierId { get; set; }
        public bool IsDeleted { get; set; }
        public bool IsAuto { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
    
        public virtual Supplier Supplier { get; set; }
        public virtual Transport Transport { get; set; }
    }
    
}
