//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace RP.Model
{
    public partial class TransportQuote
    {
        public int Id { get; set; }
        public int TransportId { get; set; }
        public int QuoteId { get; set; }
        public int TransportQuoteStatusId { get; set; }
        public Nullable<int> SelectedBy { get; set; }
        public System.DateTime SelectedDate { get; set; }
        public Nullable<int> RejectedBy { get; set; }
        public Nullable<System.DateTime> RejectedDate { get; set; }
        public Nullable<int> ConfirmedBy { get; set; }
        public Nullable<System.DateTime> ConfirmedDate { get; set; }
        public bool IsRegular { get; set; }
        public string DeclinedReason { get; set; }
        public string DeclinedComment { get; set; }
    
        public virtual Quote Quote { get; set; }
        public virtual Transport Transport { get; set; }
        public virtual TransportQuoteStatu TransportQuoteStatu { get; set; }
    }
    
}
