//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace RP.Model
{
    public partial class TransportQuoteDeclineReason
    {
        public int Id { get; set; }
        public int TransportId { get; set; }
        public int QuoteId { get; set; }
        public int TransportQuoteDeclineTypeId { get; set; }
        public string Comment { get; set; }
    
        public virtual Quote Quote { get; set; }
        public virtual Transport Transport { get; set; }
        public virtual TransportQuoteDeclineType TransportQuoteDeclineType { get; set; }
    }
    
}
