//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace RP.Model
{
    public partial class TransportReference
    {
        public int TransportId { get; set; }
        public decimal RefCost { get; set; }
        public int RefDeliveryTime { get; set; }
        public decimal RefCostPerDay { get; set; }
        public decimal RefMaxCostPerDay { get; set; }
        public decimal RefTco { get; set; }
        public decimal RefCurrencyRate { get; set; }
        public int RefCurrencyId { get; set; }
        public decimal RefHandicap { get; set; }
        public Nullable<decimal> RefExpressDeliveryPrice { get; set; }
        public decimal RefPenalty { get; set; }
    
        public virtual Currency Currency { get; set; }
        public virtual Transport Transport { get; set; }
    }
    
}
