//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace RP.Model
{
    public partial class UnityVehicleMapping
    {
        public string UnityEventId { get; set; }
        public string BuCode { get; set; }
        public int ConditionId { get; set; }
        public string TypeFile { get; set; }
    
        public virtual VehicleCondition VehicleCondition { get; set; }
    }
    
}
