//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace RP.Model
{
    public partial class User
    {
        public User()
        {
            this.Quotes = new HashSet<Quote>();
            this.Quotes1 = new HashSet<Quote>();
            this.Tariffs = new HashSet<Tariff>();
            this.Tariffs1 = new HashSet<Tariff>();
            this.TariffCategories = new HashSet<TariffCategory>();
            this.TariffCategories1 = new HashSet<TariffCategory>();
            this.TariffMinimumKms = new HashSet<TariffMinimumKm>();
            this.TariffMinimumKms1 = new HashSet<TariffMinimumKm>();
            this.TariffSurcharges = new HashSet<TariffSurcharge>();
            this.TariffSurcharges1 = new HashSet<TariffSurcharge>();
            this.Transports = new HashSet<Transport>();
            this.Transports1 = new HashSet<Transport>();
            this.TransportComments = new HashSet<TransportComment>();
            this.TransportDrafts = new HashSet<TransportDraft>();
            this.TransportDrafts1 = new HashSet<TransportDraft>();
            this.TransportHistories = new HashSet<TransportHistory>();
            this.TransportHistories1 = new HashSet<TransportHistory>();
            this.Suppliers = new HashSet<Supplier>();
        }
    
        public int Id { get; set; }
        public Nullable<int> BuId { get; set; }
        public int RoleId { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public string Email { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Department { get; set; }
        public string Position { get; set; }
        public bool IsDeleted { get; set; }
        public bool IsFirstLogin { get; set; }
    
        public virtual BusinessUnit BusinessUnit { get; set; }
        public virtual ICollection<Quote> Quotes { get; set; }
        public virtual ICollection<Quote> Quotes1 { get; set; }
        public virtual Role Role { get; set; }
        public virtual ICollection<Tariff> Tariffs { get; set; }
        public virtual ICollection<Tariff> Tariffs1 { get; set; }
        public virtual ICollection<TariffCategory> TariffCategories { get; set; }
        public virtual ICollection<TariffCategory> TariffCategories1 { get; set; }
        public virtual ICollection<TariffMinimumKm> TariffMinimumKms { get; set; }
        public virtual ICollection<TariffMinimumKm> TariffMinimumKms1 { get; set; }
        public virtual ICollection<TariffSurcharge> TariffSurcharges { get; set; }
        public virtual ICollection<TariffSurcharge> TariffSurcharges1 { get; set; }
        public virtual ICollection<Transport> Transports { get; set; }
        public virtual ICollection<Transport> Transports1 { get; set; }
        public virtual ICollection<TransportComment> TransportComments { get; set; }
        public virtual ICollection<TransportDraft> TransportDrafts { get; set; }
        public virtual ICollection<TransportDraft> TransportDrafts1 { get; set; }
        public virtual ICollection<TransportHistory> TransportHistories { get; set; }
        public virtual ICollection<TransportHistory> TransportHistories1 { get; set; }
        public virtual ICollection<Supplier> Suppliers { get; set; }
    }
    
}
