//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace RP.Model
{
    public partial class VehicleType
    {
        public VehicleType()
        {
            this.TariffCategoryVehicleTypes = new HashSet<TariffCategoryVehicleType>();
            this.TransportVehicles = new HashSet<TransportVehicle>();
            this.TransportVehicleDrafts = new HashSet<TransportVehicleDraft>();
        }
    
        public int Id { get; set; }
        public string Key { get; set; }
        public string Name { get; set; }
        public Nullable<int> OrderNumber { get; set; }
    
        public virtual ICollection<TariffCategoryVehicleType> TariffCategoryVehicleTypes { get; set; }
        public virtual ICollection<TransportVehicle> TransportVehicles { get; set; }
        public virtual ICollection<TransportVehicleDraft> TransportVehicleDrafts { get; set; }
    }
    
}
