//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RP.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class BuSupplier
    {
        public int Id { get; set; }
        public int BuId { get; set; }
        public int SupplierId { get; set; }
        public Nullable<bool> HasDiscount { get; set; }
        public Nullable<decimal> Discountpercentage { get; set; }
    
        public virtual BusinessUnit BusinessUnit { get; set; }
        public virtual Supplier Supplier { get; set; }
    }
}
