//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RP.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerBranch
    {
        public System.Guid Id { get; set; }
        public string CustomerBranchName { get; set; }
        public System.Guid CustomerId { get; set; }
        public System.Guid RegionId { get; set; }
    }
}
