//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RP.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class PatternImage
    {
        public System.Guid Id { get; set; }
        public string PatternName { get; set; }
        public string PatternImagePath { get; set; }
        public Nullable<System.Guid> CustomerId { get; set; }
        public Nullable<int> Year { get; set; }
    
        public virtual Customer Customer { get; set; }
    }
}
