//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RP.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductItemPrintOptional
    {
        public System.Guid Id { get; set; }
        public string PatternImagePath { get; set; }
        public System.Guid ProductItemId { get; set; }
        public Nullable<System.Guid> ColorCodeId { get; set; }
        public int OptionalStatusId { get; set; }
    
        public virtual DocumentProductItem DocumentProductItem { get; set; }
    }
}
