//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RP.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class SupplierNotification
    {
        public int TransportId { get; set; }
        public Nullable<int> BUId { get; set; }
        public Nullable<int> SupplierId { get; set; }
        public Nullable<int> BUEmailId { get; set; }
        public string BUEmail { get; set; }
        public Nullable<int> SupplierEmailId { get; set; }
        public string SupplierEmail { get; set; }
        public bool IsSend { get; set; }
        public Nullable<System.DateTime> ExpirationDate { get; set; }
        public bool IsBidding { get; set; }
        public Nullable<int> TransportStatusId { get; set; }
        public bool IsExpired { get; set; }
        public int IsHasQuote { get; set; }
        public System.DateTime InsertedDate { get; set; }
    }
}
