//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RP.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class TariffExpressDelivery
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TariffExpressDelivery()
        {
            this.TariffExpressDeliveryVehicleDimensions = new HashSet<TariffExpressDeliveryVehicleDimension>();
        }
    
        public int Id { get; set; }
        public int TariffId { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime LastUpdatedDate { get; set; }
        public int LastUpdatedBy { get; set; }
        public decimal PricePerKm5Days { get; set; }
        public decimal PricePerKm7Days { get; set; }
        public decimal PricePerKm10Days { get; set; }
        public bool IsDeleted { get; set; }
        public string CategoryName { get; set; }
    
        public virtual Tariff Tariff { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TariffExpressDeliveryVehicleDimension> TariffExpressDeliveryVehicleDimensions { get; set; }
    }
}
