//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RP.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class TariffCategory
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TariffCategory()
        {
            this.TariffCategoryVehicleDimensions = new HashSet<TariffCategoryVehicleDimension>();
            this.TariffCategoryVehicleTypes = new HashSet<TariffCategoryVehicleType>();
        }
    
        public int Id { get; set; }
        public int TariffId { get; set; }
        public string CategoryName { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime LastUpdatedDate { get; set; }
        public int LastUpdatedBy { get; set; }
        public decimal PricePerKm { get; set; }
        public string Description { get; set; }
        public bool IsDeleted { get; set; }
        public decimal MinimumPrice { get; set; }
    
        public virtual Tariff Tariff { get; set; }
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TariffCategoryVehicleDimension> TariffCategoryVehicleDimensions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TariffCategoryVehicleType> TariffCategoryVehicleTypes { get; set; }
    }
}
