//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RP.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class TransportAdditionalItemDraft
    {
        public int TransportDraftId { get; set; }
        public Nullable<bool> HasRoofBox { get; set; }
        public Nullable<decimal> RoofBoxWidth { get; set; }
        public Nullable<decimal> RoofBoxLength { get; set; }
        public Nullable<decimal> RoofBoxHeight { get; set; }
        public Nullable<decimal> RoofBoxWeight { get; set; }
        public string RoofBoxKeyLocation { get; set; }
        public string RoofBoxDescription { get; set; }
        public Nullable<bool> HasTrailer { get; set; }
        public Nullable<decimal> TrailerWidth { get; set; }
        public Nullable<decimal> TrailerLength { get; set; }
        public Nullable<decimal> TrailerHeight { get; set; }
        public Nullable<decimal> TrailerWeight { get; set; }
        public string TrailerDescription { get; set; }
        public Nullable<bool> HasBikeRack { get; set; }
        public Nullable<decimal> BikeRackWidth { get; set; }
        public Nullable<decimal> BikeRackLength { get; set; }
        public Nullable<decimal> BikeRackHeight { get; set; }
        public Nullable<decimal> BikeRackWeight { get; set; }
        public string BikeRackDescription { get; set; }
    
        public virtual TransportDraft TransportDraft { get; set; }
    }
}
