//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RP.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class TransportLocation
    {
        public int TransportId { get; set; }
        public string PickupGarageName { get; set; }
        public string PickupAddress { get; set; }
        public string PickupZipCode { get; set; }
        public string PickupCity { get; set; }
        public int PickupCountryId { get; set; }
        public Nullable<decimal> PickupLatitude { get; set; }
        public Nullable<decimal> PickupLongitude { get; set; }
        public string PickupPhone { get; set; }
        public string PickupOpeningHourWeekday { get; set; }
        public string PickupOpeningHourSat { get; set; }
        public Nullable<decimal> PickupStorageCost { get; set; }
        public Nullable<System.DateTime> PickupStorageStartDate { get; set; }
        public Nullable<decimal> PickupTowingCost { get; set; }
        public Nullable<decimal> PickupRepairCost { get; set; }
        public Nullable<decimal> PickupOtherCost { get; set; }
        public string DeliveryGarageName { get; set; }
        public string DeliveryAddress { get; set; }
        public string DeliveryZipCode { get; set; }
        public string DeliveryCity { get; set; }
        public int DeliveryCountryId { get; set; }
        public Nullable<decimal> DeliveryLatitude { get; set; }
        public Nullable<decimal> DeliveryLongitude { get; set; }
        public string DeliveryPhone { get; set; }
        public string DeliveryOpeningHourWeekday { get; set; }
        public decimal Distance { get; set; }
        public string PickupOpeningHourSun { get; set; }
        public string DeliveryOpeningHourSat { get; set; }
        public string DeliveryOpeningHourSun { get; set; }
        public string PickupProvince { get; set; }
        public string PickupState { get; set; }
        public string DeliveryProvince { get; set; }
        public string DeliveryState { get; set; }
        public bool IsDifferentOrigin { get; set; }
        public string OriginCity { get; set; }
        public string OriginCountry { get; set; }
        public string OriginSupplierName { get; set; }
        public decimal TcoDistance { get; set; }
        public string PaymentType { get; set; }
        public string WayPoints { get; set; }
        public string SpecialInformation { get; set; }
    
        public virtual Country Country { get; set; }
        public virtual Country Country1 { get; set; }
        public virtual Transport Transport { get; set; }
    }
}
