//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RP.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class TransportDraft
    {
        public int Id { get; set; }
        public Nullable<int> BuId { get; set; }
        public string FileNumber { get; set; }
        public string CustomerFirstName { get; set; }
        public string CustomerLastName { get; set; }
        public string CustomerPhone { get; set; }
        public Nullable<bool> IsBidding { get; set; }
        public Nullable<int> ExpirationTime { get; set; }
        public Nullable<bool> IsExpressDelivery { get; set; }
        public string Remarks { get; set; }
        public Nullable<System.DateTime> EstimateDateArrival { get; set; }
        public Nullable<System.DateTime> RealDateArrival { get; set; }
        public Nullable<int> TransportStatusId { get; set; }
        public Nullable<int> ConfirmedSupplierId { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> LastUpdatedBy { get; set; }
        public Nullable<System.DateTime> LastUpdatedDate { get; set; }
        public Nullable<System.DateTime> ExpirationDate { get; set; }
        public Nullable<int> ExpirationHour { get; set; }
        public string ExpenditureId { get; set; }
    
        public virtual BusinessUnit BusinessUnit { get; set; }
        public virtual Supplier Supplier { get; set; }
        public virtual TransportAdditionalItemDraft TransportAdditionalItemDraft { get; set; }
        public virtual TransportStatu TransportStatu { get; set; }
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
        public virtual TransportLocationDraft TransportLocationDraft { get; set; }
        public virtual TransportReferenceDraft TransportReferenceDraft { get; set; }
        public virtual TransportVehicleDraft TransportVehicleDraft { get; set; }
    }
}
