//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RP.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class TransportAssignedToSupplierCount
    {
        public int BuId { get; set; }
        public int PickupCountryId { get; set; }
        public int DeliveryCountryId { get; set; }
        public int SupplierId { get; set; }
        public int Count { get; set; }
    }
}
