//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RP.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class TransportComment
    {
        public int Id { get; set; }
        public int TransportId { get; set; }
        public string Comment { get; set; }
        public Nullable<int> CommentBy { get; set; }
        public Nullable<System.DateTime> CommentDate { get; set; }
        public bool IsRead { get; set; }
    
        public virtual Transport Transport { get; set; }
        public virtual User User { get; set; }
    }
}
