//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RP.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class TransportHistory
    {
        public int Id { get; set; }
        public int TransportId { get; set; }
        public int BuId { get; set; }
        public string FileNumber { get; set; }
        public string CustomerFirstName { get; set; }
        public string CustomerLastName { get; set; }
        public string CustomerPhone { get; set; }
        public bool IsBidding { get; set; }
        public int ExpirationTime { get; set; }
        public bool IsExpressDelivery { get; set; }
        public string Remarks { get; set; }
        public Nullable<System.DateTime> EstimateDateArrival { get; set; }
        public Nullable<System.DateTime> RealDateArrival { get; set; }
        public Nullable<int> TransportStatusId { get; set; }
        public Nullable<int> ConfirmedSupplierId { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<int> LastUpdatedBy { get; set; }
        public System.DateTime LastUpdatedDate { get; set; }
    
        public virtual BusinessUnit BusinessUnit { get; set; }
        public virtual Supplier Supplier { get; set; }
        public virtual Transport Transport { get; set; }
        public virtual TransportStatu TransportStatu { get; set; }
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
    }
}
