//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RP.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class TransportAdditionalItem
    {
        public int TransportId { get; set; }
        public bool HasRoofBox { get; set; }
        public decimal RoofBoxWidth { get; set; }
        public decimal RoofBoxLength { get; set; }
        public decimal RoofBoxHeight { get; set; }
        public decimal RoofBoxWeight { get; set; }
        public string RoofBoxKeyLocation { get; set; }
        public string RoofBoxDescription { get; set; }
        public bool HasTrailer { get; set; }
        public decimal TrailerWidth { get; set; }
        public decimal TrailerLength { get; set; }
        public decimal TrailerHeight { get; set; }
        public decimal TrailerWeight { get; set; }
        public string TrailerDescription { get; set; }
        public bool HasBikeRack { get; set; }
        public decimal BikeRackWidth { get; set; }
        public decimal BikeRackLength { get; set; }
        public decimal BikeRackHeight { get; set; }
        public decimal BikeRackWeight { get; set; }
        public string BikeRackDescription { get; set; }
    
        public virtual Transport Transport { get; set; }
    }
}
